---
title: "Untitled"
author: "Ryan Munnikhuis"
date: "8/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

```{r}
lobsters <- read_csv(here("data","Lobster_Abundance_All_Years_20210412.csv"), na = c("-99999", "")) %>% 
  clean_names() %>% 
  uncount(count)
#uncount separates values into individual data points(e.g., lobster count at 36g = 3, turns into 36g, 36g, 36g lobster.)

```

```{r}
lobster_count = lobsters %>% 
  select(site, year, size_mm) %>%
  group_by(site, year) %>% 
  summarize(mean_lobster_length = mean(size_mm, na.rm = TRUE), 
            total_count = n())


ggplot(data = lobster_count, aes(x = year, y = total_count)) + geom_point() + facet_wrap("site") + aes(color = site)
```
```{r}
lobster_2020 = lobsters %>% 
  filter(year == 2020) %>% 
  mutate(legality = case_when(
         size_mm < 79.76 ~ "illegal",
         size_mm >= 79.76 ~ "legal")) %>% 
  group_by(site, legality) %>% 
  summarize(legal_count = n()) 
         
  ggplot(data = lobster_2020, aes(x = site, y = legal_count, fill = legality)) + geom_col(position = "fill") + aes(color = legality)


```




```{r}
ex_a = lobsters %>% filter(site %in% c("IVEE", "CARP", "NAPL"))

ex_b = lobsters %>% filter(month %in% (8))

ex_C = lobsters %>% filter(site == "AQUE" | size_mm > 70)

ex_d = lobsters %>% filter(site != "NAPL")
```



```{r}
ex_e = lobsters %>% 
  group_by(site) %>%
  summarize(mean_length_site = mean(size_mm, na.rm = TRUE),
            sd_length_site = sd(size_mm, na.rm = TRUE))

ex_f = lobsters %>% group_by(month, site) %>% summarize(max_length = max(size_mm, na.rm = TRUE))

ex_g = lobsters %>% mutate(size_cm = size_mm /10)

ex_h = lobsters %>% mutate(site = tolower(site))

ex_i = lobsters %>% mutate(area = as.character(area))

ex_j = lobsters %>% mutate(size_bin = case_when(
  size_mm < 70 ~ "small",
  size_mm >= 70 ~ "large"))

ex_l = lobsters %>% mutate(designation = case_when(
  site == "IVEE" | site == "NAPL" ~ "MPA",
  site != "IVEE" | site != "NAPL" ~ "Not MPA"))
                           
```

